blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Traackr/intellij-plugin-painless-syntax-highlighting
    about: Check the README file for usage instructions.
  - name: IntelliJ Plugin Development
    url: https://plugins.jetbrains.com/docs/intellij/getting-help.html
    about: General help with IntelliJ plugin development.
